import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NavbarComponent from "../../components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pet Adoption Client",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                const savedTheme = localStorage.getItem('theme') || 'valentine';
                document.documentElement.setAttribute('data-theme', savedTheme);
              } catch (_) {}
            `,
          }}
        />
      </head>

      <body
        className="min-h-full flex flex-col bg-base-100 text-base-content"
        suppressHydrationWarning={true}
      >
        <NavbarComponent />
        <div className="flex-1">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
